language: python
python:
  - 3.8
  - 3.7
  - 3.6

cache: pip

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

script: true  # trying to add real test script

## command to run tests
#script:
#  coverage run tensorD/test_bench.py
#after_success:
#  coveralls


notifications:
  email:
    recipients:
      - zszxlsq@gmail.com
    on_success: never
    on_failure: always    # send a notification when build fail
